# Generated by Django 5.2.8 on 2025-11-06 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('min_percentage', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('thanawya', 'Thanawya Amma'), ('american', 'American Diploma'), ('igcse', 'IGCSE')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thanawya_total_marks', models.FloatField(blank=True, null=True)),
                ('american_gpa', models.FloatField(blank=True, null=True)),
                ('american_sat1_score', models.IntegerField(blank=True, null=True)),
                ('american_sat2_score', models.IntegerField(blank=True, null=True)),
                ('igcse_subjects', models.JSONField(blank=True, null=True)),
                ('final_percentage', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
