# Generated by Django 5.2.8 on 2025-12-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('major', models.CharField(choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('MED', 'Medicine'), ('BUS', 'Business'), ('ART', 'Arts & Humanities'), ('SCI', 'Natural Sciences')], max_length=50)),
                ('provider', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('duration_hours', models.IntegerField()),
                ('free', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
