# Generated by Django 5.2.8 on 2025-12-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('MED', 'Medicine'), ('BUS', 'Business'), ('ART', 'Arts & Humanities')], max_length=50),
        ),
    ]
