# Generated by Django 5.2.8 on 2025-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('fees', models.IntegerField()),
                ('credits', models.IntegerField(default=120)),
                ('required_percent', models.FloatField()),
                ('extra_requirements', models.TextField()),
                ('education_system', models.CharField(choices=[('american', 'American'), ('igcse', 'IGCSE'), ('national', 'National')], default='national', max_length=20)),
            ],
        ),
    ]
