# Generated by Django 5.2.8 on 2025-12-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_faculty_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyapplication',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('SUBMITTED', 'Form Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
