# Generated by Django 5.2.8 on 2025-12-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_facultyapplication_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyapplication',
            name='english_test_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='math_test_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='test_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='tests_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
