# Generated by Django 5.2.8 on 2025-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_facultyapplication_english_test_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyapplication',
            name='test_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='tests_completed',
            field=models.BooleanField(default=False),
        ),
    ]
